/*
 * 
 * 
 */
package UI;

import Controler.ControladorUsuario;
import javax.swing.JOptionPane;
import user.Usuario;

/**
 *
 * @author Guilherme
 */
public class UIAutenticar extends javax.swing.JDialog {

    /**
     * Creates new form UIAutenticar
     */
    public UIAutenticar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCPF = new javax.swing.JLabel();
        inputCPF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        inputSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 0, 10, 10));

        labelCPF.setText("CPF:");
        getContentPane().add(labelCPF);
        getContentPane().add(inputCPF);

        jLabel1.setText("Senha:");
        getContentPane().add(jLabel1);
        getContentPane().add(inputSenha);

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        String cpf = this.inputCPF.getText();
        char[] senha = this.inputSenha.getPassword();
        
        if (!ControladorUsuario.autenticar(cpf, senha)){
            JOptionPane.showMessageDialog(null, "CPF ou Senha inválidos!!!");
            return;
        }
        
        this.setVisible(false);
    }//GEN-LAST:event_btnEntrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JTextField inputCPF;
    private javax.swing.JPasswordField inputSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCPF;
    // End of variables declaration//GEN-END:variables

    public Usuario getUsuarioAutenticado(){
        String cpf = this.inputCPF.getText();
        return ControladorUsuario.getUsuario(cpf);
    }
}
