/*
 * 
 * 
 */
package UI;

import Clinica.Clinica;

/**
 *
 * @author Guilherme
 */
public class UIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form UIPrincipal
     */
    public UIPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        btnNovoUsuario = new javax.swing.JMenuItem();
        btnAssociarSecretarioMedico = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        btnConfirmarConsulta = new javax.swing.JMenuItem();
        btnNovaConsulta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        menuUsuario.setText("Usuários");

        btnNovoUsuario.setText("Novo usuario");
        btnNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(btnNovoUsuario);

        btnAssociarSecretarioMedico.setText("Associar Secretário a um Médico");
        btnAssociarSecretarioMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssociarSecretarioMedicoActionPerformed(evt);
            }
        });
        menuUsuario.add(btnAssociarSecretarioMedico);

        jMenuBar1.add(menuUsuario);

        menuConsultas.setText("Consultas");

        btnConfirmarConsulta.setText("Confirmar Consulta");
        menuConsultas.add(btnConfirmarConsulta);

        btnNovaConsulta.setText("Nova Consulta");
        menuConsultas.add(btnNovaConsulta);

        jMenuBar1.add(menuConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Clinica clinica = Clinica.getInstance();
        //caso não exista nenhum usuário
        if (clinica.getUsuarios().isEmpty()){
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    UIAdicionarUsuario form = new UIAdicionarUsuario(new javax.swing.JFrame(), true);
                    form.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    form.setVisible(true);
                }
            });
        }else{
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    UIAutenticar dialog = new UIAutenticar(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                }
            });
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoUsuarioActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UIAdicionarUsuario form = new UIAdicionarUsuario(new javax.swing.JFrame(), true);
                form.setVisible(true);
            }
        });
    }//GEN-LAST:event_btnNovoUsuarioActionPerformed

    private void btnAssociarSecretarioMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssociarSecretarioMedicoActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UIAssociarSecretarioMedico dialog = new UIAssociarSecretarioMedico(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
            }
        });
    }//GEN-LAST:event_btnAssociarSecretarioMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAssociarSecretarioMedico;
    private javax.swing.JMenuItem btnConfirmarConsulta;
    private javax.swing.JMenuItem btnNovaConsulta;
    private javax.swing.JMenuItem btnNovoUsuario;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuUsuario;
    // End of variables declaration//GEN-END:variables
}
