/*
 * 
 * 
 */
package ui;

import clinica.Clinica;
import controler.ControladorUsuario;
import java.util.Vector;
import javax.swing.JList;
import javax.swing.JOptionPane;
import user.Medico;
import user.Secretario;
import user.Usuario;

/**
 *
 * @author Guilherme
 */
public class UIAssociarSecretarioMedico extends javax.swing.JDialog {

    /**
     * Creates new form UIAssociarSecretarioMedico
     */
    public UIAssociarSecretarioMedico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaSecretarios = new JList<>();
        jLabel1 = new javax.swing.JLabel();
        labelMedicos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaMedicos = new JList<>();
        btnAssociar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jScrollPane1.setViewportView(listaSecretarios);

        jLabel1.setText("Seceretário:");

        labelMedicos.setText("Médico:");

        jScrollPane2.setViewportView(listaMedicos);

        btnAssociar.setText("Associar");
        btnAssociar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssociarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMedicos)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAssociar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelMedicos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAssociar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Clinica clinica = Clinica.getInstance();
        
        Vector<String> nomesSecretarios = new Vector<>();
        Vector<String> nomesMedicos = new Vector<>();
        
        for (Usuario user : clinica.getUsuarios()){
            if (user instanceof Secretario){
                nomesSecretarios.add(user.getNomeDeUsuario());
            }
            if (user instanceof Medico){
                nomesMedicos.add(user.getNomeDeUsuario());
            }
        }
        
        this.listaSecretarios.setListData(nomesSecretarios);
        this.listaMedicos.setListData(nomesMedicos);
    }//GEN-LAST:event_formWindowActivated

    private void btnAssociarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssociarActionPerformed
        String nomeSecretario = this.listaSecretarios.getSelectedValue();
        String nomeMedico = this.listaMedicos.getSelectedValue();
        
        if (nomeSecretario == null || nomeMedico == null){
            JOptionPane.showMessageDialog(null, "Médico ou Secretário não selecionado!! Por favor selecione!!");
            return;
        }
        
        if (!ControladorUsuario.associarSecretarioMedico(nomeSecretario, nomeMedico)){
            JOptionPane.showMessageDialog(null, "Médico já está asssociado a um Seceretário!!");
            return;
        }
        
        JOptionPane.showMessageDialog(null, "Médico e Seceretário associados com sucesso!!");
    }//GEN-LAST:event_btnAssociarActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssociar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelMedicos;
    private JList<String> listaMedicos;
    private JList<String> listaSecretarios;
    // End of variables declaration//GEN-END:variables
}
